### ISSUE TITLE
Add error handling and helpful messages for search input

### ISSUE THREAD

**Issue by JoshBennett793** [Jwensloff/brew-buddy#15]
The api endpoint we're using only accepts the city name. Inputting anything in addition to that, such as a 2 letter state code, prevents any update to the UI. Users need to be informed as to what the search parameters have to be. Error handling needed to provide message to user if they attempt to submit the form with an incomplete (misspelling, city doesn't exist) or improper (2 letter state code included) search parameter.

**Comment by Jwensloff** [comment]
closes #28
